spring:
  datasource:
    url: jdbc:mysql://111.229.65.208:3306/ego-shop?autoReconnect=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 111.229.65.208
    jedis:
      pool:
        max-active: 15
        max-idle: 8
        min-idle: 5
  aop:
    auto: true
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.zy.entity
  configuration: # 日志的打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
dubbo:
  application:  # 应用的名称
    id: user-service
    name: user-service
  registry: # 注册中心
    protocol: zookeeper
    address: 111.229.65.208:2181
  protocol: # 提供者监听的端口
    port: 7777
    name: dubbo
