spring:
  datasource:
    url: jdbc:mysql://111.229.65.208:3306/ego-shop
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 111.229.65.208
    jedis:
      pool:
        max-active: 15
        max-idle: 8
        min-idle: 5
  activemq:
    pool:
      enabled: true
      max-connections: 5
      max-sessions-per-connection: 20
    broker-url: tcp://111.229.65.208:61616
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.zy.entity
  configuration: # 日志的打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value:
      logic-not-delete-value:
dubbo:
  application:  # 应用的名称
    id: order-service
    name: order-service
  registry: # 注册中心
    protocol: zookeeper
    address: 111.229.65.208:2181
  protocol: # 提供者监听的端口
    port: 2222
    name: dubbo
